#!/usr/bin/env bash
# curl test script generated by Apinox
# API: Pet Store API v1.0.0
# Run with: bash curl_tests.sh

set -euo pipefail

BASE_URL="https://petstore.example.com/v1"

echo "=== pets ==="

# List all pets - GET
curl -s -w '\nHTTP Status: %{http_code}\n' -X GET -H 'Authorization: Bearer ${TOKEN}' 'https://petstore.example.com/v1/pets'

# Create a pet - POST
curl -s -w '\nHTTP Status: %{http_code}\n' -X POST -H 'Authorization: Bearer ${TOKEN}' -H 'Content-Type: application/json' -d '{}' 'https://petstore.example.com/v1/pets'

