#!/usr/bin/env bash
# curl test script generated by Apinox
# API: atomix-cloud-api v1.0.0
# Run with: bash curl_tests.sh

set -euo pipefail

BASE_URL="https://cloud.denisetiya.site/api"

echo "=== Authentication ==="

# Initiate GitHub OAuth - GET
curl -s -w '\nHTTP Status: %{http_code}\n' -X GET -H 'Authorization: Bearer ${TOKEN}' 'https://cloud.denisetiya.site/api/auth/github'

# GitHub OAuth Callback - GET
curl -s -w '\nHTTP Status: %{http_code}\n' -X GET -H 'Authorization: Bearer ${TOKEN}' 'https://cloud.denisetiya.site/api/auth/github/callback'

# Get Current User - GET
curl -s -w '\nHTTP Status: %{http_code}\n' -X GET -H 'Authorization: Bearer ${TOKEN}' 'https://cloud.denisetiya.site/api/auth/me'

# Logout - POST
curl -s -w '\nHTTP Status: %{http_code}\n' -X POST -H 'Authorization: Bearer ${TOKEN}' 'https://cloud.denisetiya.site/api/auth/logout'

# List User GitHub Repos - GET
curl -s -w '\nHTTP Status: %{http_code}\n' -X GET -H 'Authorization: Bearer ${TOKEN}' 'https://cloud.denisetiya.site/api/auth/github/repos'

echo "=== Deployments ==="

# Trigger Deployment - POST
curl -s -w '\nHTTP Status: %{http_code}\n' -X POST -H 'Authorization: Bearer ${TOKEN}' 'https://cloud.denisetiya.site/api/projects/{id}/deploy'

# List Deployments - GET
curl -s -w '\nHTTP Status: %{http_code}\n' -X GET -H 'Authorization: Bearer ${TOKEN}' 'https://cloud.denisetiya.site/api/projects/{id}/deployments'

# Get Deployment - GET
curl -s -w '\nHTTP Status: %{http_code}\n' -X GET -H 'Authorization: Bearer ${TOKEN}' 'https://cloud.denisetiya.site/api/deployments/{id}'

# Get Deployment Logs - GET
curl -s -w '\nHTTP Status: %{http_code}\n' -X GET -H 'Authorization: Bearer ${TOKEN}' 'https://cloud.denisetiya.site/api/deployments/{id}/logs'

echo "=== Projects ==="

# List Projects - GET
curl -s -w '\nHTTP Status: %{http_code}\n' -X GET -H 'Authorization: Bearer ${TOKEN}' 'https://cloud.denisetiya.site/api/projects'

# Create Project - POST
curl -s -w '\nHTTP Status: %{http_code}\n' -X POST -H 'Authorization: Bearer ${TOKEN}' -H 'Content-Type: application/json' -d '{"name":"atomix-cloud","repo_branch":"main","repo_url":"https://github.com/denisetiya/atomix-cloud.git"}' 'https://cloud.denisetiya.site/api/projects'

# Get Project - GET
curl -s -w '\nHTTP Status: %{http_code}\n' -X GET -H 'Authorization: Bearer ${TOKEN}' 'https://cloud.denisetiya.site/api/projects/{id}'

# Update Project - PUT
curl -s -w '\nHTTP Status: %{http_code}\n' -X PUT -H 'Authorization: Bearer ${TOKEN}' -H 'Content-Type: application/json' -d '{}' 'https://cloud.denisetiya.site/api/projects/{id}'

# Delete Project - DELETE
curl -s -w '\nHTTP Status: %{http_code}\n' -X DELETE -H 'Authorization: Bearer ${TOKEN}' 'https://cloud.denisetiya.site/api/projects/{id}'

