#!/usr/bin/env bash
# curl test script generated by Apinox
# API: atomix-cloud-modular v1.0.0
# Run with: bash curl_tests.sh

set -euo pipefail

BASE_URL="https://api.denisetiya.site/v1"

echo "=== Products ==="

# List Products - GET
curl -s -w '\nHTTP Status: %{http_code}\n' -X GET -H 'Authorization: Bearer ${TOKEN}' 'https://api.denisetiya.site/v1/products'

