use anyhow::Result;

use crate::schema::endpoint::Body;
use crate::schema::root::ApinoxSchema;

/// Hurl file content + companion curl shell script
pub struct HurlOutput {
    pub hurl: String,
    pub curl_script: String,
}

/// Generate Hurl file from schema
pub fn generate(schema: &ApinoxSchema) -> Result<String> {
    let hurl = build_hurl_file(schema);
    Ok(hurl)
}

/// Generate both Hurl file and curl companion script
pub fn generate_all(schema: &ApinoxSchema) -> Result<HurlOutput> {
    let hurl = build_hurl_file(schema);
    let curl_script = build_curl_script(schema);
    Ok(HurlOutput { hurl, curl_script })
}

/// Build the complete .hurl file
fn build_hurl_file(schema: &ApinoxSchema) -> String {
    let mut output = String::new();

    // Header comment
    output.push_str("# Hurl test file generated by Apinox\n");
    output.push_str(&format!("# API: {} v{}\n", schema.name, schema.version));
    if let Some(ref desc) = schema.description {
        output.push_str(&format!("# {}\n", desc));
    }
    output.push_str(&format!(
        "# Base URL: {}\n",
        schema.base_url.as_deref().unwrap_or("(not set)")
    ));
    output.push('\n');

    // Group endpoints
    let grouped = group_endpoints(schema);

    for (group_name, endpoints) in &grouped {
        if group_name != "__ungrouped__" {
            output.push_str(&format!("### {} ###\n\n", group_name));
        }

        for ep in endpoints {
            output.push_str(&format!("{}\n\n", build_hurl_block(schema, ep)));
        }
    }

    output
}

/// Group endpoints by their group field
fn group_endpoints(
    schema: &ApinoxSchema,
) -> Vec<(String, Vec<&crate::schema::endpoint::Endpoint>)> {
    let mut groups: std::collections::BTreeMap<String, Vec<&crate::schema::endpoint::Endpoint>> =
        std::collections::BTreeMap::new();

    for ep in &schema.endpoints {
        let key = ep
            .group
            .as_ref()
            .and_then(|g| {
                schema
                    .groups
                    .iter()
                    .find(|grp| grp.id == *g)
                    .map(|grp| grp.name.clone())
                    .or_else(|| Some(g.clone()))
            })
            .unwrap_or_else(|| "__ungrouped__".to_string());

        groups.entry(key).or_default().push(ep);
    }

    // Move ungrouped to end
    let ungrouped = groups.remove("__ungrouped__");
    let mut result: Vec<(String, Vec<&crate::schema::endpoint::Endpoint>)> =
        groups.into_iter().collect();

    if let Some(ungrouped) = ungrouped {
        if !ungrouped.is_empty() {
            result.push(("__ungrouped__".to_string(), ungrouped));
        }
    }

    result
}

/// Build a single Hurl request block for an endpoint
fn build_hurl_block(schema: &ApinoxSchema, ep: &crate::schema::endpoint::Endpoint) -> String {
    let mut block = String::new();
    let method = ep.method.to_uppercase();
    let url = build_url(schema, ep);

    // Comments
    if let Some(ref desc) = ep.description {
        block.push_str(&format!("# Endpoint: {}\n# {}\n", ep.name, desc));
    } else {
        block.push_str(&format!("# Endpoint: {}\n", ep.name));
    }
    if ep.deprecated {
        block.push_str("# DEPRECATED\n");
    }
    block.push_str(&format!("# {} {}\n", method, ep.path));

    // Method + URL
    block.push_str(&format!("{} {}\n", method, url));

    // Query params
    if !ep.query_params.is_empty() {
        block.push_str("[QueryStringParams]\n");
        for p in &ep.query_params {
            let val = p
                .default
                .as_ref()
                .map(|v| v.to_string())
                .unwrap_or_default();
            block.push_str(&format!("{}: {}\n", p.name, val));
        }
    }

    // Headers
    if !ep.headers.is_empty() {
        block.push_str("[Headers]\n");
        for h in &ep.headers {
            let val = h.value.as_deref().unwrap_or("");
            block.push_str(&format!("{}: {}\n", h.name, val));
        }
    }

    // Auth — add Authorization header if scheme is bearer
    let auth_id = ep.auth.as_deref().or(schema.auth.default.as_deref());
    if let Some(scheme_id) = auth_id {
        if let Some(scheme) = schema.auth.schemes.iter().find(|s| s.id == scheme_id) {
            if let Some("bearer") = scheme.scheme.as_deref() {
                block.push_str("[Headers]\n");
                block.push_str("Authorization: Bearer {{token}}\n");
            }
        }
    }

    // Body
    if let Some(ref body) = ep.body {
        block.push_str(&build_body_block(body));
    }

    // Assertions from first successful response
    if let Some(resp) = ep
        .responses
        .iter()
        .find(|r| r.status >= 200 && r.status < 300)
    {
        block.push_str(&format!("[Assert]\nstatus == {}\n", resp.status));

        // If the response has a schema, add jsonpath assertions
        if let Some(ref schema_map) = resp.schema {
            for field in schema_map.keys() {
                block.push_str(&format!("[Assert]\njsonpath \"$.{}\" exists\n", field));
            }
        }
    } else if let Some(resp) = ep.responses.first() {
        block.push_str(&format!("[Assert]\nstatus == {}\n", resp.status));
    }

    block.trim_end().to_string()
}

/// Build the body section of a Hurl block
fn build_body_block(body: &Body) -> String {
    match body.body_type.as_str() {
        "json" => {
            let example = body
                .examples
                .first()
                .map(|ex| {
                    serde_json::to_string_pretty(&ex.value).unwrap_or_else(|_| "{}".to_string())
                })
                .unwrap_or_else(|| "{}".to_string());

            format!("[Body]\n```json\n{}\n```\n", example)
        }
        "formdata" => {
            let mut block = String::from("[MultipartFormData]\n");
            if let Some(ref fields) = body.fields {
                for f in fields {
                    let default_val = f
                        .default
                        .as_ref()
                        .map(|v| v.to_string())
                        .unwrap_or_default();
                    block.push_str(&format!("{}=\"{}\"\n", f.name, default_val));
                }
            }
            block
        }
        "urlencoded" => {
            let mut block = String::from("[Body]\n");
            if let Some(ref schema) = body.schema {
                let map: serde_json::Map<String, serde_json::Value> = schema
                    .iter()
                    .map(|(k, v)| {
                        let val = v
                            .default
                            .as_ref()
                            .cloned()
                            .unwrap_or_else(|| serde_json::Value::String(String::new()));
                        (k.clone(), val)
                    })
                    .collect();
                if let Ok(json_str) = serde_json::to_string_pretty(&serde_json::Value::Object(map))
                {
                    block.push_str(&format!("```\n{}\n```\n", json_str));
                }
            }
            block
        }
        "binary" => {
            let mime = body
                .mime_type
                .as_deref()
                .unwrap_or("application/octet-stream");
            format!("[Body]\n```{}\n(file contents)\n```\n", mime)
        }
        "raw" => {
            let example = body
                .examples
                .first()
                .map(|ex| match &ex.value {
                    serde_json::Value::String(s) => s.clone(),
                    other => serde_json::to_string_pretty(other).unwrap_or_default(),
                })
                .unwrap_or_default();
            let ct = body.content_type.as_deref().unwrap_or("text/plain");
            format!("[Body]\n```{}\n{}\n```\n", ct, example)
        }
        _ => String::new(),
    }
}

/// Build full URL for an endpoint
fn build_url(schema: &ApinoxSchema, ep: &crate::schema::endpoint::Endpoint) -> String {
    let base = ep
        .servers
        .as_ref()
        .and_then(|s| s.production.as_ref())
        .or(schema.base_url.as_ref())
        .map(|s| s.trim_end_matches('/').to_string())
        .unwrap_or_else(|| "http://localhost".to_string());

    let path = if ep.path.starts_with('/') {
        ep.path.clone()
    } else {
        format!("/{}", ep.path)
    };

    format!("{}{}", base, path)
}

/// Generate a companion shell script with curl equivalents
fn build_curl_script(schema: &ApinoxSchema) -> String {
    let mut output = String::new();

    output.push_str("#!/usr/bin/env bash\n");
    output.push_str("# curl test script generated by Apinox\n");
    output.push_str(&format!("# API: {} v{}\n", schema.name, schema.version));
    output.push_str("# Run with: bash curl_tests.sh\n\n");
    output.push_str("set -euo pipefail\n\n");

    // Base URL variable
    let base = schema.base_url.as_deref().unwrap_or("http://localhost");
    output.push_str(&format!("BASE_URL=\"{}\"\n\n", base));

    let grouped = group_endpoints(schema);

    for (group_name, endpoints) in &grouped {
        if group_name != "__ungrouped__" {
            output.push_str(&format!("echo \"=== {} ===\"\n\n", group_name));
        }

        for ep in endpoints {
            output.push_str(&format!("{}\n\n", build_curl_command(schema, ep)));
        }
    }

    output
}

/// Build a curl command for an endpoint
fn build_curl_command(schema: &ApinoxSchema, ep: &crate::schema::endpoint::Endpoint) -> String {
    let method = ep.method.to_uppercase();
    let url = build_url(schema, ep);

    let mut lines: Vec<String> = Vec::new();

    // Comment
    lines.push(format!("# {} - {}", ep.name, method));

    let mut cmd = String::from("curl -s");
    cmd.push_str(" -w '\\\\nHTTP Status: %{http_code}\\\\n'");
    cmd.push_str(&format!(" -X {}", method));

    // Headers
    for h in &ep.headers {
        if let Some(ref val) = h.value {
            cmd.push_str(&format!(" -H '{}: {}'", h.name, val));
        }
    }

    // Auth
    let auth_id = ep.auth.as_deref().or(schema.auth.default.as_deref());
    if let Some(scheme_id) = auth_id {
        if let Some(scheme) = schema.auth.schemes.iter().find(|s| s.id == scheme_id) {
            match scheme.auth_type {
                crate::schema::auth::AuthType::Http => {
                    let token_type = scheme.scheme.as_deref().unwrap_or("bearer");
                    if token_type == "bearer" {
                        cmd.push_str(" -H 'Authorization: Bearer ${TOKEN}'");
                    } else if token_type == "basic" {
                        cmd.push_str(" -u '${USERNAME}:${PASSWORD}'");
                    }
                }
                crate::schema::auth::AuthType::ApiKey => {
                    let key_name = scheme.key.as_deref().unwrap_or("X-API-Key");
                    cmd.push_str(&format!(" -H '{}: ${{API_KEY}}'", key_name));
                }
                crate::schema::auth::AuthType::Basic => {
                    cmd.push_str(" -u '${USERNAME}:${PASSWORD}'");
                }
                _ => {}
            }
        }
    }

    // Body
    if let Some(ref body) = ep.body {
        match body.body_type.as_str() {
            "json" => {
                let example = body
                    .examples
                    .first()
                    .map(|ex| serde_json::to_string(&ex.value).unwrap_or_default())
                    .unwrap_or_else(|| "{}".to_string());
                cmd.push_str(" -H 'Content-Type: application/json'");
                cmd.push_str(&format!(" -d '{}'", example));
            }
            "formdata" => {
                if let Some(ref fields) = body.fields {
                    for f in fields {
                        let val = f
                            .default
                            .as_ref()
                            .map(|v| v.to_string())
                            .unwrap_or_default();
                        cmd.push_str(&format!(" -F '{}={}'", f.name, val));
                    }
                }
            }
            "urlencoded" => {
                cmd.push_str(" -H 'Content-Type: application/x-www-form-urlencoded'");
                if let Some(ref schema_map) = body.schema {
                    let form_data: Vec<String> = schema_map
                        .iter()
                        .map(|(k, v)| {
                            let val = v
                                .default
                                .as_ref()
                                .map(|d| d.to_string())
                                .unwrap_or_default();
                            format!("{}={}", k, val)
                        })
                        .collect();
                    cmd.push_str(&format!(" -d '{}'", form_data.join("&")));
                }
            }
            "raw" => {
                let ct = body.content_type.as_deref().unwrap_or("text/plain");
                let example = body
                    .examples
                    .first()
                    .map(|ex| match &ex.value {
                        serde_json::Value::String(s) => s.clone(),
                        other => serde_json::to_string(other).unwrap_or_default(),
                    })
                    .unwrap_or_default();
                cmd.push_str(&format!(" -H 'Content-Type: {}'", ct));
                cmd.push_str(&format!(" -d '{}'", example));
            }
            _ => {}
        }
    }

    // Append URL at end
    cmd.push_str(&format!(" '{}'", url));

    lines.push(cmd);
    lines.join("\n")
}
